cmake_minimum_required(VERSION 4.2)
project(dsa_lab)

set(CMAKE_CXX_STANDARD 14)

add_executable(dsa_lab
        lab1/ok1.cpp
        lab1/ok2.cpp
        lab1/ok3.cpp
        lab1/ok4.cpp
        lab1/reverse1.cpp
        lab1/two_sum.cpp
        lab1/duplicate.cpp
        lab1/duplicate_2.cpp
        lab2/linear1.h
        lab2/mainlb2.cpp
        lab2/q1.cpp
        lab2/q2.cpp
        lab2/q3.cpp
        lab2/q4.cpp
        lab2/q5.cpp
        lab2/q6.cpp
        lab2/q7.cpp
        lab2/q8.cpp
)
